# Configuration for probot-stale - https://github.com/probot/stale

# Number of days of inactivity before an Issue or Pull Request becomes stale
daysUntilStale: 12
# Number of days of inactivity before a stale Issue or Pull Request is closed
daysUntilClose: 7
# Issues or Pull Requests with these labels will never be considered stale
exemptLabels:
  - bug
  - Announcement
  - help wanted
  - To investigate
  - pinned
  - security
# Label to use when marking as stale
staleLabel: stale
# Comment to post when marking as stale. Set to `false` to disable
markComment: >
  This is Robo-lampros because the Human-lampros is lazy. This issue has been automatically
  marked as stale because it has not had recent activity. It will be closed after 7 days if
  no further activity occurs. Feel free to re-open a closed issue and the Human-lampros 
  will respond.
